### ISSUE TITLE
Mac OSX - GOFMT not running

### ISSUE THREAD

**Issue by zymtom** [earthspace/brackets-gofmt#1]
I tried to click and run it, but it won't run at all. I saw the message saying i should symlink both here and in the plugin itself, but, i have this weird bug where I litterarly can't get root on my PC without re-installing completely, which isn't too fun.

I can run gofmt from my cli by just typing gofmt, so why can't brackets find it?

**Comment by earthspace** [comment]
There's an odd situation with Brackets that I haven't fully understood regarding permissions. It's possible that it may work if you run brackets from the terminal with sudo. Otherwise the only solution that I've found is to make the symlink. 

(OT: after a lot of messing around with brackets, I found that sublimetext+gosublime was an easier solution for coding Go).
